== Un Extracto de la Vida de Patrick Livingston

Está en mi corazón declarar algo de lo que ha tenido que atravesar mi alma,
por el bien de aquellos que están anhelando al Señor, y quienes,
aunque puede que hayan experimentado algún cambio notorio,
todavía no han llegado al verdadero lugar de satisfacción. Por el bien de estos,
declararé algo de la bondad, clemencia, misericordia y amor de Dios para con mi alma,
para que, al leerlo,
otros puedan mirar dentro de sí mismos y considerar sus propias condiciones.

Ahora puedo mirar hacia atrás y traer a la memoria y recordar,
cuán cerca estaba el Señor de mí, incluso cuando yo estaba muy lejos de Él en mi mente.
En verdad, debido al mal que se alojaba en mi corazón, yo estaba muy lejos de Él,
y aun así, Él estaba cerca de mí y me cuidaba noche y día, aunque yo era un tonto,
que estaba entenebrecido y ciego,
y no podía discernir Su cuidado sobre mí. Él estaba
cerca de mí en Sus juicios para abatirme y humillarme,
y para que pudiera aprender a conocerme a mí mismo y a conocerlo a Él. ¡Oh alma mía,
alaba al Señor por siempre, por toda la eternidad,
porque Sus misericordias están sobre todas Sus obras!

En aquel tiempo el Señor me guardó de cometer inmundicias
evidentes y manifiestas a las que veía que otros corrían;
sin embargo, era desenfrenado, feroz y apasionado, y ligero y vano en mi mente,
ya que no había llegado a conocer mi cabestro ni mi freno.
Y no estaba libre de una voluntad perversa ni de
fuertes inclinaciones a toda clase de vicio,
pero el Señor estaba cerca de mí, aun cuando yo no conocía Su cercanía ni Su presencia,
y evitó que hiciera o cometiera los más grandes males a los que mi corazón se inclinaba.
Así que, en ese tiempo, me di cuenta de que la semilla de toda maldad obraba en mí,
y que brotaba con múltiples deseos e inclinaciones al mal; pero el Señor estaba presente,
y me detenía y me lo impedía. Y cuando todavía era joven,
a veces se levantaba en mí angustia y gran miedo,
pero no sabía a qué. Pero como era de un espíritu desenfrenado,
alejaba rápidamente el temor al seguir mis inclinaciones malvadas y vacías,
de una vanidad a otra.
Sin embargo, a medida que crecía el miedo aumentaba en mí, junto con la angustia.

Un notable suceso está fresco en mi memoria.
En una oportunidad abrí las Escrituras y puse mis ojos en
ese lugar en 2 Tesalonicenses 1:7-10 donde está escrito:
"`...cuando se manifieste el Señor Jesús desde el cielo con los ángeles de Su poder,
en llama de fuego, para dar retribución a los que no conocieron a Dios,
ni obedecen al evangelio de nuestro Señor Jesucristo;
los cuales sufrirán pena de eterna perdición,
excluidos de la presencia del Señor y de la gloria de Su poder,
cuando venga en aquel día para ser glorificado en sus santos y ser admirado en todos
los que creyeron (por cuanto nuestro testimonio ha sido creído entre vosotros).`"
Y debido al temor que se levantó cuando leí esta Escritura,
puse el libro a un lado y comencé a distraerme otra vez,
de modo que se alejó por un tiempo,
y yo continué tras mi mente vana y vacía en mi juego o pasatiempo (como es llamado).
Pero en la noche cuando me fui a la cama, el miedo me despertó muchas veces,
y por la mañana regresó a mi mente la misma Escritura.
Recuerdo muy bien lo que surgió en mi corazón en
ese momento--una convicción de mi ignorancia de Dios,
de que yo no lo conocía a Él verdaderamente.
Y habiendo leído en esa Escritura que "`cuando el Señor Jesús se
manifieste desde el cielo con los ángeles de Su poder,
en llama de fuego, para dar retribución a los que no lo conocieron,
ni obedecen al evangelio de nuestro Señor Jesucristo;
los cuales sufrirán pena de eterna perdición,
excluidos de la presencia de Dios y de la gloria de Su poder`"--habiendo leído esto,
brotó en mi corazón,
y fue llevado directo a mi conciencia por la luz
o semilla de vida (que en ese entonces no conocía),
_que yo era uno de los que no conocían a Dios;_
y que si vivía y moría en esa ignorancia de Dios,
entonces sería uno de los que Él haría sufrir con la pena de eterna
perdición. Y entonces se levantó un deseo en mí de conocer a Dios,
a partir de una convicción en mí mismo de que no lo conocía. Y en ese
momento me levanté y me puse de rodillas al lado de mi cama y oré,
conforme a la pobre y débil capacidad que tenía en ese entonces,
rogando que de alguna manera pudiera llegar al conocimiento de Dios.

Ahora bien,
esa era la presencia del Señor conmigo--un tierno brote
de la semilla de vida y de la aparición de Su luz en mí,
convenciéndome de mi ignorancia de Dios, y por un tiempo,
despertando un deseo en mí de conocer a Dios.
Sin embargo, cuán rápidamente era apagado y velado esto, y echado de mi vista,
por mi espíritu ocupado e inquieto, que permanecía sin descanso en mi ligereza,
libertad carnal y locura.
A veces esa misma consciencia se levantaba nuevamente en mi memoria,
pero duraba muy poco tiempo (como un vistazo muy rápido que se desvanecía otra vez),
porque mi vaso no estaba preparado para retener algo tan
serio respecto a Dios y a mi propia condición. Sin embargo,
debo decir que en ese entonces el Señor realmente
se estaba despertando y moviendo en mi mente;
no solo en ese tiempo,
que en verdad fue el primer y más notable toque de Su Espíritu que había experimentado,
sino también en otros tiempos, tanto antes como especialmente después de esto;
pero ¡ay! todos ellos fueron muy poco tenidos en cuenta por mí.

Después de esto, las angustias aumentaron gradualmente sobre mí;
y siendo propenso a enfermarme, eso también era usado como un medio para humillarme.
Y cuando mi incansable espíritu natural era humillado por enfermedades o aflicciones,
entonces me daba cuenta de que la luz estaba cerca para aparecer en mí,
no solo para permitirme ver lo que estaba mal en mi vida (según mi capacidad de percibirlo,
la cual entonces era muy pequeña y pobre),
sino también para llevar o inclinar mi mente a lo que era bueno.
Esto también era el gran amor de Dios,
y debo confesar que en ese tiempo no había ningún defecto en la luz,
sino que los defectos eran muchos y grandes en mí. Y aunque en ese entonces
estaba casi completamente entregado a la vanidad y ligereza de mi mente,
el Señor tenía cuidado de mí como Su criatura, y más aún,
tenía cuidado de esa semilla que yacía en prisión dentro de mí,
a veces gimiendo por libertad, despertándose y moviéndose contra el mal,
y atrayéndome al Señor con tiernos deseos,
aun cuando el curso y corriente que fluían más fuerte en mí, y por lo que era arrastrado,
era lo que se oponía a Su luz o semilla.
Y entonces, cuando estaba entre todos mis compañeros, si alguno me miraba,
poco o nada de seriedad religiosa podía ver en mí según la vista u observación externa;
porque en verdad, me daba vergüenza confesar o reconocer abiertamente,
eso que se estaba despertando en mí,
aunque muchas veces ablandaba y quebrantaba mi corazón en secreto,
y se levantaba un clamor a Dios.

Pero ¡oh!, me daba vergüenza que alguien supiera de esto, y lo cubría con ligereza,
vanidad y desenfreno.
¡Cómo no maravillarme del amor,
misericordia y gran paciencia de Dios cuando recuerdo estas cosas,
de cómo me soportó el Señor y no me cortó en esa malvada condición! Aunque yo por mucho
tiempo fui de corazón desobediente y no quería responder al amor de Dios,
aun así esa luz o semilla que brotaba en mí era buena, santa,
salvadora y suficiente en su naturaleza.
Mi corazón era como un suelo malo, que no estaba preparado para recibirlo a Él,
y por la abundancia de cosas malas que brotaban en mí desde la semilla del mal,
la buena semilla estuvo por mucho tiempo ahogada y apagada,
y no podía brotar para dar frutos de justicia.
Pero aun así,
una medida de Su luz permanecía en la tierra de mi corazón como una semilla santa,
que se movía una y otra vez.
De modo que debo decir otra vez, en la sinceridad y rectitud de mi corazón,
que la luz o semilla siempre fue buena en todos sus brotes y movimientos,
y que nunca encontré ninguna carencia, debilidad o defecto en ella;
sino que toda la carencia,
debilidad y defectos estaban en la tierra en mí que
no estaba preparada para recibir la semilla,
sino que a menudo la ahogaba y la resistía.

Sucedió entonces, cuando llegué a años de mayor entendimiento,
que permanecí por un tiempo en Leith y Edinburgh,
y comencé a frecuentar las reuniones de los Presbiterianos,
y más especialmente las de aquellos que eran llamados Remonstrantes.
Pero me di cuenta de que seguía teniendo un sentido de descontento,
tanto conmigo mismo como con ellos,
aunque en ese entonces no conocía a ninguno que fuera
igual a ellos o que hubiera ido más allá de ellos.
Mi deseo y mi clamor hacia Dios se incrementaban y encontraba
una continua insatisfacción conmigo mismo;
y sentía dudas de que estuviera en lo correcto.
Aunque puedo decir con verdad,
que en ese entonces mi ternura no era menor sino mayor que antes,
y que había una medida de seriedad que también estaba comenzando a aparecer externamente,
aunque me daba vergüenza dejarla aparecer mucho, y a menudo luchaba por ocultarla.

Ahora veo que el Señor siempre estuvo conmigo en Su luz y semilla santa,
y que en este tiempo la contrariedad y enemistad
entre las dos semillas se hacían cada vez más evidentes,
aunque en ese entonces mi entendimiento era muy débil,
y no podía discernir o hacer una verdadera diferencia entre lo precioso y lo vil en
mí. Pero la luz seguía en mí como una semilla santa que no tenía paz con el mal,
y en ella y por ella mi paz era quebrantada diariamente.
Encontré algo en mí que de buena gana hubiera apagado la luz,
porque era una angustia para mí,
y un tormento para una parte en mí que vivía y no estaba dispuesta a morir.
Y era esta luz la que siempre me hacía sentir descontento y disgustado conmigo mismo,
porque ella me mostraba lo que no estaba bien en mí y en otros,
y todo lo que no estaba en paz con el Señor. Y ahora sé por una amplia y buena experiencia,
que es la naturaleza de esta luz o semilla, estar disgustada con todo el mal,
y con todos los que unen su voluntad al mal;
pero que tiene complacencia en todo lo que es bueno, santo y verdadero,
y en todos los que están unidos al bien.

Me di cuenta de que la luz se complacía,
en la medida que yo salía del mal y entraba al bien,
porque en esa medida yo tenía un sentido de tranquilidad y paz.
Pero había otras cosas alojándose en mí corazón que no se veían externamente,
las cuales la luz aborrecía,
y por esta razón mi alma a menudo estaba bajo muchos pesos y cargas.
En ese entonces era débil y tenía poco discernimiento,
y por eso consideraba como malas para mí, cosas que en realidad eran para mi bien.
Porque la luz que traía angustia y carga sobre mí era buena,
pero la causa de la angustia era mala.
Y yo podía sentir que el poder o semilla del mal producía numerosas concupiscencias
y deseos malos en mí. Era consciente de ellos y eran una carga pesada para mí,
de modo que me sentía cansado de ellos, pero no sabía cómo vencerlos.
Y ahora, cuando miro hacia atrás mi condición,
veo claramente qué era lo que hacía que mis malos pensamientos y mi mente
errante e inconstante fueran un peso y una carga para mí;
era la luz que se había levantado en mí en una medida pequeña,
y que estaba levantándose diariamente, revelando mi condición y mostrándome el mal.
En verdad, ella era la causa de toda mi angustia,
y la razón por la que a menudo sentía juicio y condenación;
porque el mal y la desobediencia se alojaban en mí
y hacían que la ira de Dios reposara sobre mí,
y que Su ira ardiera en mí como un fuego, para que la causa de ella pudiera ser removida.
Entonces, cuando sentía eso,
se levantaban fuertes deseos y clamores al Señor pidiéndole alivio y ayuda,
y le hacía muchas promesas y votos secretos al Señor,
de que sería Suyo si tan solo me daba libertad y me redimía.
A menudo determinaba vigilar mi corazón y mis pensamientos,
porque estaba consciente de que mis pensamientos eran sobremanera malos;
y cuanto más brillante aparecía la luz en mí,
más claramente veía la maldad e infidelidad de mi corazón, y mis pensamientos errantes,
los cuales se hacían cada vez más sobremanera pecaminosos y aborrecibles a mi vista.
Y sin embargo,
en ese tiempo yo no sabía que la luz por la cual podía ver y entender estas cosas,
era la gracia y luz salvadora y suficiente de Jesucristo,
aunque sí sabía y reconocía que había algo en mí que me
permitía ver mi corazón y mis pensamientos.

Entonces caí en cierta angustia mental,
porque esos hombres llamados ministros decían que había dos luces;
una que llamaban la luz del evangelio, que era salvadora y suficiente,
y que sólo estaba en los creyentes; y otra que llamaban común e insuficiente.
Así que estaba confundido en mi mente,
sin saber cuál de estas dos luces era la que me permitía ver mi corazón y mis pensamientos,
concluyendo en algunos momentos que era una, y en otros la otra.
Ellos nos decían que los que sólo tenían la luz común o natural podían llegar
muy lejos cumpliendo todos los deberes cristianos (como ellos los llamaban),
y sin embargo, no tener nada de esta gracia salvadora y suficiente en ellos;
y esto perturbaba mi mente aún más, y me causaba mucha angustia.
Grande en verdad era mi deseo en aquel entonces de tener
la luz y gracia verdaderas y salvadoras del evangelio,
de las que los había oído hablar; pero, ay, ellos (mis maestros) no las conocían,
y ¿cómo iba yo a conocerlas realmente mientras siguiera escuchando sus ciegas distinciones?
Porque ellos daban marcas o señales de cómo podían
conocer las personas la gracia o luz salvadora,
y si la teníamos o no; y sin embargo,
en otras ocasiones decían que los hipócritas podían tener la mayoría o todas esas marcas,
y aun así no tener nada de la luz y gracia salvadoras.

Y así fui llevado de aquí para allá, junto con muchas otras almas pobres y tiernas,
por los vientos de sus doctrinas inestables, inciertas y contradictorias,
muchas veces contradiciéndose a sí mismos y entre sí. Y cuando les preguntábamos
cómo podíamos conocer la verdadera luz y gracia del evangelio,
entonces nos ponían a escuchar, leer y orar más,
diciéndonos que continuáramos en estos y otros deberes,
esperando el conocimiento de la luz y gracia especial.
Y puedo decir esto con honestidad, que con la poca fuerza que tenía,
corría de uno de estos maestros a otro,
deseando fervientemente conocer ese poder que me podía salvar,
porque todavía era sensible del mal en mi corazón y de lo errante de mis pensamientos.
Pero debido a estas distinciones falsas,
fui llevado (a través de las sugerencias de Satanás y de mi propio
corazón malvado) a ignorar y a menospreciar esa luz que ya conocía,
considerándola débil e insuficiente.
Y debido a que veía que mi mente era peor que antes,
y que mis pensamientos eran aún más propensos a ser
errantes que antes de que hiciera profesión religiosa,
muchas veces concluí que su doctrina era cierta respecto a la luz en mí,
y que todavía no había encontrado la luz que era salvadora y suficiente.

Así desprecié la luz que diariamente me mostraba mi condición y ablandaba mi corazón,
abriendo cada vez más ante mi vista la maldad de mi corazón y de mis pensamientos.
Y sin embargo, junto con los hombres que eran llamados ministros,
le eché la culpa de esto a la luz; aunque en verdad no había defecto o debilidad en ella,
sino que el defecto y la debilidad se encontraban en mí y en estos maestros,
quienes con sus distinciones falsas confundían nuestras mentes,
nos apartaban de la luz y nos ponían a esforzarnos en nuestras propias voluntades,
a seguir nuestros propios espíritus, luchando y esforzándonos en prácticas externas,
yendo de una a otra, corriendo de un hombre a otro,
buscando al que vive entre los muertos.
Y así yo, con muchas más almas pobres y simples, fuimos desviado por estos maestros,
quienes en lugar de volver mi corazón y el de otros a la luz de Cristo en nuestro interior,
nos apartaron de ella, llamándola oscura y sombría, débil y natural,
e insuficiente para llevarnos a Dios.

Y así anduvimos errantes de un lado a otro,
siendo llevados de aquí para allá interna y externamente,
y teniendo en poca estima esta luz, tal como Israel menospreció su maná, diciendo:
"`Nuestra alma tiene fastidio de este pan tan liviano.`"^
footnote:[Números 21:5]
Pero aunque era llamado maná (que significa: "`¿Qué es?`"), algo que ellos no conocían,
aun así era el alimento que Dios había provisto para ellos.
Y así, al igual que ellos, por dejar la provisión de Dios,
no tuvimos otra alternativa más que seguir nuestras propias voluntades,
o las voluntades de nuestros maestros,
aunque seguimos clamando a Dios y haciendo muchas
oraciones pidiendo que Su Espíritu Santo nos ayudara.

Y aunque yo y muchos otros luchamos y nos esforzamos mucho en prácticas externas,
(y muchos habían luchado en estas cosas por mucho más tiempo que yo),
ahora estoy plenamente convencido por el Señor,
de que mientras el hombre viva en estos tabernáculos,
nunca encontrará otra luz que pueda mostrarle la verdad,
ni sacarlo del mal y llevarlo a los bienes que se experimentan en la luz.
Porque nunca he hallado paz y descanso para mi alma fuera
de lo que brota en mí cuando creo y sigo esta luz.
Y durante todo el tiempo que seguí a estos maestros,
mi alma no tuvo descanso y estuvo en angustia,
juicio y condenación. La ira del Señor ardía en mí y no tenía victoria,
y aunque a menudo la buscaba diligentemente con muchas lágrimas,
aun así no podía obtenerla, porque me apartaba de eso en lo que se encontraba mi paz,
y buscaba otra.
Así agoté y fatigué mi espíritu y cuerpo natural, y traje gran angustia a mi alma.

Fue alrededor de este tiempo que al Señor le plació que
escuchara a dos personas del pueblo llamado Cuáqueros,
y mi alma fue muy alcanzada al escucharlos.
Ellos dieron testimonio de la luz, diciendo que era la luz de Cristo en mí,
y "`en todo hombre que viene al mundo,`"^
footnote:[Juan 1:9]
la que yo había estado despreciando como algo común e insuficiente,
conforme a lo que mis maestros me habían enseñado.
En verdad,
las palabras de uno de estos hombres llegaron mucho a mi
entendimiento mientras lo oía hablar respecto a la luz;
y ambos fueron de mucha ayuda para mí, y algo en mi dijo "`Amén`" a lo que predicaron.
Así mi mente llegó a ser más dirigida a esta luz, y a creer en ella.

Ahora, esto no era algo nuevo para mí,
porque estaba muy consciente de que dicha luz estaba
en mí incluso antes de haberlos visto,
o haber escuchado algo acerca del pueblo llamado Cuáqueros.
Pero una cosa en su testimonio sí era nueva para mí,
el hecho de que ellos me dirigieran a esta luz,
e insistieran en que todos debían ir a ella, llevar todas sus obras a ella,
creer en ella y andar en ella,
y que ella era capaz de llevar a Dios a todos los que creyeran en ella y la siguieran.
Esto en verdad era nuevo para mí,
y contrario a lo que había oído de los hombres llamados ministros,
que enseñaban una doctrina totalmente contraria respecto
a esa luz con la que todo hombre es alumbrado.
Porque estos me habían dicho que ella no era ni salvadora
ni suficiente para llevar a Dios;
tampoco me enseñaron a llevar mis pensamientos, palabras y obras a esta luz,
para ser dirigido y guiado por ella.

Pero ¡ay!, después de haber oído a estos hombres llamados Cuáqueros,
mi angustia se hizo incluso más grande que antes
porque no obedecí la luz de Cristo en mí,
ni dejé a los maestros que negaban esta luz,
y que me habían alejado de ella por tanto tiempo,
haciéndome errar y divagar en tinieblas.
Sin embargo, su espíritu y doctrina contra la luz habían penetrado tanto en mí,
que aunque había sido muy alcanzado por el testimonio de los siervos del Señor,
el espíritu y doctrina contrarios no fueron echados fácilmente,
y la serpiente hizo uso de ellos por algunos años,
impidiendo que me entregara completamente en obediencia.
Y puedo decir, que aunque mi angustia era grande antes,
fue mucho más grande (por un tiempo) después de haber oído
ese testimonio bueno y fiel respecto a la luz de Cristo;
hasta que dejé a esos maestros.
No puedo declarar la gran angustia de mi alma, o la perplejidad de mi mente,
que vino justamente sobre mí de parte del Señor por mi desobediencia.

Porque a veces iba a escuchar a los Cuáqueros (así llamados),
y a veces iba a escuchar a los ministros (como eran llamados),
y a veces iba a los Bautistas y a los Independientes,
pues en ese entonces había de todas estas denominaciones
en Leith y Edinburgh cuando los ingleses estaban en Escocia.
Por un tiempo no me uní a ninguno de ellos en lo absoluto,
pero estaba más inclinado al pueblo llamado Cuáqueros,
aunque tenía muchos temores y dudas sobre si unirme a ellos o no,
porque la vieja levadura se interponía mucho en mi camino para estorbarme,
y mi confusión era grande.
Cuando oía a los Cuáqueros, ellos me exhortaban a creer en la luz,
y a que abandonara cualquier mal que ella descubriera,
y a que amara y siguiera el bien que mostrara.
Pero cuando escuchaba a los ministros,
ellos me decían que la luz no era capaz de sacarme de todo el mal que ella me mostraba,
ni de llevarme al bien.

Y los escuchaba clamar unos contra otros; los Bautistas contra los Presbiterianos,
los Presbiterianos contra los Bautistas e Independientes,
los Independientes contra los Bautistas y Presbiterianos;
y los Presbiterianos estaban divididos en dos grupos,
uno llamado '`The Public Resolutioners`',
y el otro llamado '`Remonstrators`'. Un tipo de Presbiterianos clamaba contra el otro,
y contra todos los demás grupos a quienes llamaban "`sectas.`"
Pero noté que todos ellos estaban en contra de los Cuáqueros;
porque aunque estaban divididos entre ellos y clamaban unos contra otros, sin embargo,
todos inclinaban sus fuerzas contra los Cuáqueros y contra
la luz que solían llamar la "`luz de los Cuáqueros,`" citando
Escrituras y tratando de torcerlas contra esta luz.

Ahora bien,
observar todas estas cosas le causaba una angustia no pequeña a mi mente,
ya que no sabía a quién unirme;
porque las tinieblas se habían apoderado tanto de mí por mi desobediencia,
que estaba confundido en mi mente con todo lo que oía que estos
maestros de todas las denominaciones hablaban contra la luz.
Sin embargo,
todavía había en mi corazón un amor secreto hacia
ese pueblo y hacia su testimonio acerca de la luz;
pero siendo débil y frágil,
y no pudiendo ver más allá de las cosas sutiles y astutas que los ministros alegaban,
estaba confundido y no podía refutarlos.
Porque los que predicaban contra los Cuáqueros y la luz,
clamaban cuán horrendo era seguir las tinieblas en lugar de la luz;
porque ellos decían que seguir una luz falsa era lo mismo que seguir las tinieblas.
Y en realidad, esto es cierto, e incluso en ese entonces yo lo creía,
pero era aplicado perversamente a los Cuáqueros y a la luz que predicaban.
Y en verdad, después de haber oído lo que los Cuáqueros testificaban respecto a la luz,
nunca me atreví a aceptar en mi corazón lo que los ministros decían contra ella,
aunque sus palabras me confundían y me angustiaban.
Porque aunque había un miedo en mí de concluir absolutamente
que los testimonios de los Cuáqueros eran verdaderos,
aun así no me atrevía a negarlos, ni a decir que eran falsos.

Pero a veces me venía el pensamiento de que el Señor Jesús
y todos Sus seguidores habían sido aborrecidos y perseguidos;
y que estos predicadores de la luz se veían mucho más como Cristo
y Sus apóstoles que cualquiera de esos que predicaban contra ella.
Esto muchas veces me hacía sentir un gran miedo y temor,
porque no quería estar del lado de aquellos que negaban la aparición de Cristo en Espíritu,
tal como los judíos habían negado Su aparición en la carne.
Y la inocencia,
paciencia y sufrimientos de estos predicadores de la luz me tocaban mucho, de modo que,
aunque en ese entonces no me uní a ellos (siendo detenido
por la sutileza de la serpiente y sus perversos instrumentos),
aun así, mi corazón se inclinaba todo el tiempo principalmente a estar con ellos,
y nunca me atreví a dejar que alguna conclusión contra ellos entrara y se estableciera
en mi corazón. Incluso en las cosas que todavía no podía ver,
había un miedo en mí de juzgarlos, no fuera que por mi ignorancia o debilidad,
condenara la Verdad en ellos.

Pero el deseo de estar completamente claro y satisfecho
respecto a la luz pesaba fuertemente sobre mí,
y mi clamor al Señor era que Él me resolviera plenamente este asunto,
y me concediera una certeza absoluta al respecto,
porque de este asunto dependía el fundamento mismo y la base de la diferencia
entre los predicadores de la luz de Cristo y los que se oponían a ella.
Y en verdad, encontré como verdadero,
(incluso mientras viajaba a través de este tiempo de mucha angustia y prueba)
_que cada vez que seguía a esta luz en cualquier cosa,
era el tiempo en que tenía paz._
Pero cuando actuaba en contra de ella, no podía encontrar otra luz,
ni ningún hombre que fuera capaz de consolarme.

Ahora puedo mirar hacia atrás y ver plenamente el gran amor de Dios para conmigo,
quien me persiguió con Sus juicios y Sus misericordias.
Y asimismo puedo mirar hacia atrás y ver que la luz,
que apareció primero en mí y me dejó ver mi ignorancia de Dios,
era la misma luz que aparecía cada vez más en mí,
para mostrarme tanto el mal dentro de mí como fuera
de mí. Y que cuanto más obediente me volvía a ella,
más crecía mi luz en mí y brillaba más claramente,
y el mal se mostraba aún más ofensivo y abominable,
y sobremanera pecaminoso en mí. Encontré siempre como certero,
que a medida que mi mente se apartaba de cualquier
cosa que era manifestada y reprobada por la luz,
entonces la luz no me reprobaba más por dicha cosa, a menos que volviera a ella otra vez.
De modo que ahora verdaderamente experimento y puedo dar
testimonio de la pureza de la naturaleza de esta luz,
de cómo ella no condena en lo absoluto al justo, ni justifica al impío,
sino que su naturaleza misma siempre ha sido, es y será hasta el fin,
justificar al justo y condenar al impío.

Y ahora todos ustedes que se oponen a esta luz,
muéstrenme dónde se puede encontrar otra luz aparte de esta,
que universalmente ejecute su oficio, a saber, justificar al justo y condenar al impío;
porque todos los seguidores de la luz de Cristo pueden dar testimonio conmigo,
y yo con ellos, de que la luz es una y siempre la misma en su naturaleza,
la cual es pura y santa.
Y podemos mirar hacia atrás ahora, y ver dentro de nosotros mismos,
que la luz antes estaba en nosotros como una pequeña semilla bajo el suelo,
mientras éramos tinieblas y corríamos tras ellas.
La luz en ese entonces resplandecía en nuestras tinieblas, es decir,
resplandecía en nosotros cuando estábamos en el estado de tinieblas,
y todavía no habíamos acudido a esta luz o semilla;
aun así ella se movía y resplandecía en nosotros como un humilde testigo,
que siempre testificaba contra nosotros cuando estábamos en nuestra condición natural.
Y en verdad, aunque en ese entonces era la única luz que teníamos en ese estado oscuro,
aun así, si en algo hacíamos el bien,
y nos apartábamos del mal en cualquier cosa por más pequeña que fuera,
la naturaleza de esta luz era siempre justificar lo bueno y condenar lo malo.

Pero a medida que crecíamos hacia una manifestación más plena de la misma luz,
más hallábamos la perla y el tesoro.
De modo que,
hasta en la peor condición en la que se pueda encontrar un hombre
(que no continuó en el pecado hasta que su día de gracia expiró),
esta luz es de la misma naturaleza y género,
tal cual está en el hombre en la mejor condición. Porque no existe ninguna condición
en la que un hombre se pueda encontrar que altere la naturaleza de la luz,
aunque ella sí varía en cuanto a la medida y grado de su manifestación,
y también en su operación en los diferentes estados.
Por lo tanto, para el hombre que no se mantuvo pecando hasta que su día se agotó,
no hay ningún estado o lugar sino en el que tiene algo de luz,
y en el que la luz que tiene es santa,
y la naturaleza de la luz es justificar siempre al
que anda en ella y condenar al que la resiste.

Y esto testificamos con verdad, fidelidad y experiencia:
Que incluso antes de llegar a conocer la luz de Cristo,
ella ya estaba dentro de nosotros.
Que cuando caminábamos en tinieblas y estábamos en un estado oscuro, ella estaba ahí,
y resplandecía en nosotros mientras estábamos en ese estado,
manifestándonos cualquier cosa que fuéramos capaces de ver en ese tiempo,
y reprendiéndonos y condenándonos por el mal.
Y aunque no nos condenaba por las maldades de las cuales
no éramos culpables (en cuanto al acto externo de ellas),
sí condenaba la naturaleza de todo mal en nosotros.
Que después de que habíamos alcanzado un conocimiento mayor de esta bendita luz o semilla,
que el que teníamos cuando resplandeció por primera
vez en nuestras tinieblas (cuando éramos tinieblas),
ella empezó a resplandecer de las tinieblas y a darnos
"`la luz del conocimiento de la gloria de Dios,
en la faz de Jesucristo.`"^
footnote:[2 Corintios 4:6]
Entonces el tesoro que yacía escondido en nosotros
fue encontrado y experimentado en el vaso de barro.
Y así,
hemos hallado que la naturaleza del tesoro o perla es la
misma cuando está escondida y resplandece _en_ las tinieblas,
y cuando resplandece _de_ las tinieblas.
De modo que, de nuevo, el defecto no está en la perla o tesoro (o luz o semilla),
sino en el hombre o mujer en quien aparece.
Y ahora puedo mirar hacia atrás y justificar la luz en mi propio corazón y alma,
y despejarla de toda acusación;
viendo claramente que toda la culpa y defecto estaban en mí,
y de ninguna manera en esta luz o semilla de Cristo.

Pero si alguien me preguntara, cómo llegué a esta certeza y satisfacción, le respondo,
_solo al entregarme en obediencia a la luz, para andar en ella._
Porque aquí encontré un fundamento firme o garantía para creer en esta luz,
y para unirme a sus seguidores, y también,
un buen fundamento para rechazar a todos los que se oponen a ella.
Y ahora puedo decir por una amplia experiencia,
que la he encontrado verdadera e infalible en todo lo que me ha enseñado.
Pero hasta que no tomé la decisión firme y estable
de aferrarme a las cosas que aprendía en la luz,
y de seguirla a dondequiera que me llevara,
nunca estuve en paz o tuve descanso en mi mente,
sino que era llevado de una opinión a otra.
Y por otra parte,
decidí firmemente no meterme en esas cosas que no me habían sido reveladas claramente,
en alguna medida, como verdaderas; porque si eran dudosas las dejaba a un lado,
y me aferraba a esas cosas que eran infaliblemente ciertas para mí.

Pero si se preguntara, cuáles son estas cosas.
Respondo, que por una larga experiencia,
llegué a estar completamente seguro y plenamente persuadido y satisfecho en mi corazón,
de que la naturaleza de esta luz era buena y santa,
debido a la bondad y pureza de las cosas que me enseñaba a seguir,
y por el testimonio que daba en mí _contra_ toda maldad.
Porque yo no conocí ni el bien ni el mal,
salvo en la medida que esta luz me enseñaba a ver y a discernir
entre eso que es realmente bueno y eso que es realmente malo.
Es cierto que había oído hablar mucho de Dios y de Cristo,
y que había leído mucho las Escrituras,
y que tenía muchos buenos testimonios de muchas cosas buenas,
y muchos testimonios contra cosa malas;
pero nunca hubiera podido creer o conocer por experiencia la verdad de estos testimonios,
si no hubiese sido por esta luz.
De modo que cualquier conocimiento verdadero del testimonio de
las Escrituras (tanto a favor del bien como en contra del mal)
lo recibí y obtuve por el brillo de esta luz en mí,
por el cual hallé que ella era verdadera y santa en su naturaleza,
al grabar en mi mente una verdadera conciencia o instinto por el
cual conocí infaliblemente algunas cosas que eran buenas;
como por ejemplo, que había un solo Dios santo y verdadero, quien en Sí Mismo es bondad,
amor, santidad y pureza.

Por esta luz también fui capaz de sentir
al espíritu maligno e impío oponiéndose a esa cosa buena y santa en mí;
y no pude encontrar nada más en mí, ni en ningún otro lugar,
que me dejara ver y percibir tanto el mal como el bien.
Y también vi que la naturaleza y semilla maligna y maldita no se oponía a nada en mí,
tanto como se oponía _al continuo volver de mi mente a esta luz;_
ni pude jamás encontrar otra luz en mí,
que me moviera a amar y a seguir la pureza y la santidad,
y a dejar el mal y la injusticia.
Y cuando actuaba en contra de esta luz, haciendo lo que ella me mostraba que era malo,
entonces me golpeaba y me reprobaba, y hablaba angustia a mi corazón,
y no encontraba nada que pudiera darme paz, hasta que volvía de nuevo a esta luz,
y abandonaba el mal.
En verdad nunca encontré nada aparte de esta luz
que yo pudiera decir que era santo en su naturaleza,
que me enseñaba santidad y me dejaba ver el mal, y que me juzgaba cuando hacía algo malo,
y me hablaba paz cuando hacía algo bueno.
Y he hallado que esto es infaliblemente verdadero.

En verdad,
de ninguna manera podría discernir nada que fuera celestial o divino,
si no fuera por esta luz que me deja ver tanto lo
que es celestial y divino como lo que no es.
Ni podría reconocer correctamente lo que es pecado y lo que no lo es, sin esta luz.
Porque yo podía imitar a otros, y repetir lo que otros habían dicho,
pero no podía sentir verdadera certeza, sin esta luz.
Esta era mi paz y satisfacción,
y puedo atestiguar que mi paz y satisfacción siguen aumentando,
_al vivir de acuerdo con esta luz en todas las cosas,
que en el tiempo presente conozco con certeza; es decir,
por aferrarme al bien revelado y evadir el mal._
Antes de llegar a esta decisión en mi corazón, nunca tuve ninguna paz que permaneciera.
Nunca encontré paz por razonar o disputar en mi mente,
sino solo al vivir y caminar en esa medida de bien que conocía con certeza,
y apartarme del mal.
De este modo,
mi paz creció dentro de mí. Pero mientras me mantuve discutiendo y razonando,
y disputando en mi mente, o argumentando con otros sobre la luz,
nunca pude encontrar paz, más bien solo dolor y angustia.
Pero cuando vino a mi mente de manera fuerte y poderosa el deseo
de seguir y obedecer eso en lo que consistía mi paz,
esto se volvió mi fundamento y garantía para confiar en Dios,
y para mirarlo a Él y esperar Su ayuda.
Y al estar firmemente establecido en esto, mi paz brotó abundantemente.

Una cosa que me confirmó fuertemente en mi decisión,
fue que me di cuenta de que esta luz coincidía y cumplía todos
los testimonios que las Escrituras daban acerca de la luz verdadera,
del Espíritu verdadero o de la Semilla verdadera de Dios.
De modo que,
cualquier cosa que la Escritura declarara sobre las poderosas obras
realizadas por este santo poder y Espíritu en el interior de los
corazones de cualquiera de las personas santas que vivieron antiguamente,
encontraba que esta luz hacía lo mismo,
que realizaba la misma obra poderosa en todos los que la seguían. Y en verdad,
a medida que crecía en su poder y virtud, experimentaba la misma obra forjada en mí,
por esta luz que los santos hombres de Dios habían
experimentado por el Espíritu de Cristo.
Y a medida que me llevaba a experimentar las mismas obras de santidad y pureza de mente,
me sacaba del mundo, y me daba victoria sobre él y sobre sus males,
esto me confirmaba cada vez más,
que la luz (la que los que se oponen llaman "`natural e insuficiente`") era en
verdad suficiente para llevarme a la misma experiencia santa de salvación,
tanto interna como externamente.
Entonces brotó un gran amor en mi corazón hacia aquellos
que daban testimonio de esta luz;
porque al experimentar que su obra en mí era exactamente lo que ellos describían,
ahora sabía que su testimonio era verdadero.
En verdad, nada de lo que ellos decían de su poder y suficiencia fallaba.
Al contrario,
descubrí que la virtud y poder de esta luz era aún mayor
que todo lo que ellos habían dicho de ella.

Por lo tanto, pueblos todos, aférrense a eso que es cierto y seguro;
porque es cierto y seguro que esta luz está en ustedes (de la cual damos testimonio),
y que ella les muestra esas cosas que son buenas y malas.
Y a medida que lleven sus pensamientos, palabras y obras a Su luz,
llegarán a una mayor claridad de entendimiento, y a ver,
que tanto nuestro testimonio de la luz como nuestro testimonio contra sus maestros,
son verdaderos; y que el testimonio de ellos contra nosotros y contra la luz es falso.

[.discourse-part]
_Objeción:_ Pero es algo peligroso y un gran mal,
tomar como luz verdadera y salvadora la que no lo es;
porque eso sería engañar a nuestras propias almas.

[.discourse-part]
_Respuesta:_
Así como es muy peligroso y destructivo tomar como luz verdadera la que no lo es,
no es menos peligroso y destructivo rechazar y negar
la luz verdadera cuando realmente lo es;
porque los que no creen en la luz verdadera,
deben inevitablemente poner algo que es falso en su lugar,
poniendo las tinieblas por luz, y la luz por tinieblas.
Ahora bien, ¿pueden ustedes decir que la luz que encuentran en sus corazones,
de la cual damos testimonio, no es la luz verdadera?
¿Están seguros,
o tienen algún conocimiento certero de que esa no es la
luz verdadera de Cristo resplandeciendo en ustedes?
¿O, pueden decir que han encontrado otra luz que les muestra lo que está en sus corazones?
Porque esta luz de la que hablamos sí les muestra muchas cosas,
tanto en sus pensamientos, como en sus palabras y obras.
¿Han encontrado una luz aparte de esta luz, que les muestre más de lo que esta muestra,
o que siempre los guíe al bien y los aparte del mal?
Ahora consideren, sin luz ustedes no podrían ver estas cosas; pero ustedes sí las ven,
y encuentran que son descubiertas o puestas en evidencia por una luz en sus corazones,
tal como el apóstol dice: "`Todas las cosas que son reprobadas,
son hechas manifiestas por la luz, porque lo que manifiesta todo, es la luz.`"^
footnote:[Efesios 5:13 Reina Valera de Gómez]
¿No hay algo en ustedes que manifiesta y descubre muchos pensamientos,
palabras y acciones, y que también los reprueba?
Ese algo es la luz, y a esa luz deben prestarle atención, y en ella deben creer,
de lo contrario no podrán llegar a Cristo o seguirlo verdaderamente.

[.discourse-part]
_Objeción:_ Si esta es la luz verdadera y salvadora en la que todos debemos creer,
¿por qué no la experimentamos llevándonos fuera de los males,
e introduciéndonos en las cosas buenas que ella nos muestra?

[.discourse-part]
_Respuesta:_ "`Cristo vino a los suyos, y los suyos no lo recibieron,
mas a todos los que lo recibieron, les dio poder para ser hechos hijos de Dios.`"^
footnote:[Juan 1:11-12]
Ahora, ¿por qué Él no les dio poder a los otros,
a quienes llamó "`los suyos`"? ¿No fue porque ellos
"`no lo recibieron`"? Él vino a ellos,
pero ellos no lo recibieron.
Así vemos que Aquel que vino a los que no lo recibieron,
era verdaderamente un salvador suficiente, pero ellos, al no recibirlo,
no recibieron Su poder.
Y sin embargo, este mismo Cristo, "`que desecharon los edificadores,`"^
footnote:[Mateos 21:42, Lucas 20:17]
_fue_ recibido por otros, y en Él recibieron poder para ser hechos hijos de Dios,
habiendo creído en Su nombre.

De la misma manera, Cristo es la Luz del mundo,
y "`alumbra a todo hombre que viene al mundo.`"^
footnote:[Juan 1:9 Reina Valera de Gómez]
Él viene a todos con Su luz, y los que creen en Él y lo siguen,
no permanecen en tinieblas; sino que, al seguirlo en la luz,
salen de las tinieblas a la experiencia de la luz y del
conocimiento de Su vida en el interior de sus corazones.
Pero los que no creen en la luz que viene a ellos, no salen de las tinieblas,
sino que permanecen en ellas; porque no creen en la luz,
ni siguen a Cristo en esa luz que aparece en ellos para sacarlos de las tinieblas.
Sin embargo, la luz que está en ellos tiene poder para salvar,
y les muestra muchos males que aman más que a la luz que los expone y reprueba.
Y la luz también les muestra muchas cosas buenas que ellos no llegan a poseer,
porque no la siguen con la intención de andar en ella, y por lo tanto,
no siguen verdaderamente a Cristo.

[.discourse-part]
_Objeción:_ ¿Podemos seguir la luz por nuestras propias fuerzas?
¿Cómo puede ser esto, si no tenemos ningún poder por nosotros mismos?

[.discourse-part]
_Respuesta:_ Ustedes no pueden por sí mismos, sin Cristo, hacer nada que sea bueno.
Pero hay tiempos y momentos de vida en los cuales el Señor Jesucristo, la Luz,
viene y visita los corazones de las personas,
y manifiesta en ellos (por el tiempo presente) lo que de Dios se puede conocer.^
footnote:[Romanos 1:19 "`Porque lo que se conoce
acerca de Dios es evidente dentro de ellos,
pues Dios se lo hizo evidente.`"
LBLA]
Estos son los tiempos de vida^
footnote:[Véase Lucas 19:44, Juan 6:44, 65; Cantares 1:4; Salmos 10:3;
también Génesis 18:10-14.],
cuando los hombres y las mujeres tienen que entregarse al Señor en la luz,
para seguirlo e ir en pos de Él; y cuando Él contiende en ellos y con ellos,
y los atrae con Su Luz.
Porque entonces hay poder presente,
y es posible entregarse a Él y seguirlo con el poder que ellos tienen de Él en la luz.
Porque incluso como hombre natural, o incluso con respecto a lo natural, no puedo hablar,
ni oír, ni ver, ni hacer nada por mí mismo sin Dios; y sin embargo,
encuentro poder para hacer todas estas cosas, tanto para hablar, ver, oír,
etc. como para abstenerme a veces.
Tengo esos poderes de Dios, y puedo usarlos bien, o puedo abusar de todos ellos.
Pero si abuso de este poder, me tengo que culpar a mí mismo y no al Señor,
que me ha dado ojos para ver el peligro; porque si yo quiero correr al peligro,
tengo que culparme a mí mismo y no al Señor, porque podría haber hecho otra cosa.

Ahora bien, así como el Señor ha provisto todas las cosas buenas para el hombre natural,
así también lo ha hecho para el alma,
la parte más importante (la cual es más correctamente llamada
"`el hombre`") que esa parte que es mortal y corruptible.
Por lo tanto, Él le ha dado luz al alma y poder para usar la luz; y sin embargo,
yo también podría abusar de mi medida de luz y entendimiento.
En realidad, es muy posible abusar de ella; pero si lo hago,
tengo que culparme a mí mismo y no al Señor,
que me ha iluminado con una luz que es tanto verdadera, como salvadora y suficiente.
Pero yo también podría usar esta luz para la salvación de mi alma en Cristo,
y mirar a Aquel que es la fuente de la luz y de la vida.
Cuando he usado Su luz, no ha sido por mis propias fuerzas, sin Cristo,
sino que por Él y con el poder que he recibido de Él,
hago lo que es agradable ante Sus ojos.
Y si hago lo malo, entonces tengo que culparme a mí mismo,
por abusar del poder que me había sido dado para
hacer lo que era agradable ante Sus ojos.

Por lo tanto, que ningún hombre diga:
"`Carezco de poder para hacer lo que le agrada a Dios.`"
Ciertamente , ustedes pueden abusar del poder que Dios les ha dado, y por ende,
carecer del uso correcto
del poder o habilidad que se les ha dado;
pero no carecen de poder mientras no hayan agotado
el día de su visitación al continuar en sus pecados.
Porque el hombre no puede ser condenado por lo que de verdad carece y nunca ha tenido.
Pero si ustedes fallan en el ejercicio del poder que Dios les ha dado,
y su día de visitación aún no ha terminado,
sino que sienten al Espíritu del Señor contendiendo todavía en y con ustedes,
entonces sí tienen algo de poder.
Les digo, no es que a ustedes les falte poder, sino que, por su desobediencia al poder,
y por no entregarse en obediencia a la luz y Espíritu de Dios,
ustedes mismos rehúsan ejercer el poder que Dios ha plantado en sus corazones en la luz;
y por esta razón deben culparse a sí mismos y no
al Señor. Porque el Espíritu del Señor no los reprobaría,
juzgaría ni condenaría por su desobediencia,
si realmente carecieran de poder para obedecer;
porque lo que deben obedecer está dentro de sus corazones, ofreciéndoles su poder.
Y si esto no estuviera en sus corazones, y ustedes en verdad no lo tuvieran,
no podría decirse que lo desobedecen,
ni el Juez justo de toda la tierra los condenaría
y reprendería por no obedecer algo que no tienen.
Pero la razón por la que sienten reprensiones y condenación,
es porque ustedes _sí tienen_ luz,
y tienen poder para usar la luz para el fin por el cual se les ha dado; y sin embargo,
abusan de este poder, se rebelan contra la luz, y no quieren llevar sus obras a ella.
Ustedes en verdad, pudieron haber hecho esto, y todavía lo pueden hacer,
mientras el Espíritu del Señor contienda en ustedes y con ustedes.
Por lo tanto, mientras el Espíritu del Señor se encuentre contendiendo con ustedes,
no digan más que no tienen poder; porque no carecen ni de luz ni de poder,
sino que por su desobediencia a la luz y su abuso del poder,
carecen del ejercicio del poder para la gloria de Dios,
y para el consuelo de su propia alma.

[.discourse-part]
_Objeción:_
Pero yo no tengo poder sobre la maldad de mi corazón. Esta es mi aflicción y mi carga,
y estaría contento de deshacerme de los pensamientos malos,
ociosos y vanos que se levantan en mi mente, y sin embargo,
soy consciente de mi inhabilidad de vencerlos.
¿No se puede decir entonces,
que carezco de poder sobre mis pensamientos y sobre la maldad de mi corazón?

[.discourse-part]
_Respuesta:_ Tú tienes un poder que no usas, y por lo tanto,
solo careces del ejercicio de ese poder que ya tienes.
Y mientras que tu mente no esté puesta en esa luz que Dios ha plantado en ti,
y no aprendas a obedecer y a ser ejercitado por ella,
no podrás obtener victoria sobre tus pensamientos ni sobre la maldad de tu corazón,
ni ser libre de estas cosas.

Los tiempos,
condiciones y estados de las personas deben ser considerados--porque
todas tienen tiempos de visitación,
en los que tienen poder según sus capacidades para ver, juzgar, querer,
entender y actuar lo que es bueno, y también para evitar lo que es malo.
Pero por la desobediencia al poder que Dios les ha dado (tanto natural como espiritual),
por la rebelión contra él, y por la dureza,
descuido y desprecio de dicho poder ellas pueden
(y muchas lo hacen) perder todo el poder que tienen;
sí, ¡e incluso toda la voluntad de hacer el bien!
Pero aun así,
durante el día o tiempo de vida mientras el Espíritu del Señor contiende con los hombres,
a ellos no les falta poder para vencer sus malos pensamientos,
si creen en la luz y usan el poder que Dios les ha dado.

[.discourse-part]
_Objeción:_
Es cierto que encuentro un deseo de vencer la maldad de mis pensamientos y de mi corazón,
pero aun así no encuentro el poder para hacerlo.

[.discourse-part]
_Respuesta:_ Muchos profesan creer en Dios y en Cristo,
pero es necesario conocer y creer en la luz de Su
vida y salvación que ha sido plantada en tu corazón,
y que manifiesta el verdadero estado de tu corazón y tus pensamientos.
"`Todas las cosas que son reprobadas, son hechas manifiestas por la luz,
porque lo que manifiesta todo, es la luz.
Por lo cual dice: Despiértate, tú que duermes, y levántate de los muertos,
y te alumbrará Cristo.`"^
footnote:[Efesios 5:13-14 Reina Valera de Gómez]
Esta luz ha sido designada por Dios para llevarte a Él en Cristo Jesús,
fuera de toda muerte y oscuridad.
Pero si no crees que esta luz ha resplandecido en tu corazón con este fin,
y si no te entregas a obedecerla y a andar en ella,
sino que la desprecias como algo común e insuficiente, incapaz de llevarte a Dios,
entonces, aunque toda esa perspectiva verdadera que tienes venga de Dios,
aun así nunca encontrarás poder sobre la maldad de tu corazón y de tus pensamientos.
Y nunca encontrarás otra luz que sea capaz de darte
poder y victoria sobre la maldad de tu corazón,
aparte de la única luz que te ha dado la capacidad de ver y conocer el mal.

Pero aunque sientes esta luz en ti, que es poderosa en tu corazón,
visitándote y mostrándote tu corazón y tus pensamientos,
aun así la menosprecias como algo común e insuficiente,
y buscas algún otro camino de redención, por algún otro medio diferente a este.
Y cuando el enemigo de tu alma te encuentra todavía desobedeciendo
y menospreciando la medida de la luz de Cristo que ya tienes,
y buscando otro camino u otra cosa,
él mantiene su fortaleza en tu corazón que no puede ser tomada ni vencida,
sino a medida que creas y andes en la luz de Cristo que está en ti.
Y en verdad, puedes correr de una cosa a otra, pero todo será en vano,
y al final serás sepultado en dolor.

[.discourse-part]
_Objeción:_ Parece haber mucho peligro en ambos lados.
Por un lado,
está el peligro de estar de acuerdo y unirme a algo que _no_ es la luz verdadera y salvadora;
y por el otro,
está el peligro de negar y despreciar eso que es la luz verdadera y salvadora.
Y estando en tan grande aprieto, y careciendo de discernimiento respecto a qué unirme,
¿qué se puede hacer en este triste caso?

[.discourse-part]
_Respuesta:_ No existe ese aprieto así como tú lo percibes,
porque el camino es tanto fácil como placentero para la mente dispuesta,
una que está real y verdaderamente dispuesta a entregarse a eso que es certero y seguro.
Porque Dios no ha escondido de ti eso que es absolutamente
necesario para tu bienestar presente;
sino que Él lo ha hecho, lo hace y lo hará simple y fácil de entender;
y a medida que te entregues a ello, Dios hará que sea sumamente fácil para ti obedecer,
y así el camino se vuelve placentero para la mente dispuesta.

Ahora considera esta Escritura en Génesis 3:15: "`Dios dijo a la serpiente:
Pondré enemistad entre ti y la mujer, y entre tu simiente y la Simiente suya,`" etc.
Ahora la enemistad y contrariedad se encuentra entre las dos semillas,
y estas son las dos semillas que están en enemistad dentro de ti, la una contra la otra.
No se dice que habrá enemistad entre ninguna otra simiente,
sino solo entre la simiente de la serpiente y la Simiente de la mujer.

Ahora la buena semilla es la Semilla de la mujer,
y la mala semilla es la semilla de la serpiente,
y la diferencia y contienda se encuentra entre estas dos semillas en toda la humanidad.
¿No encuentras dos semillas o naturalezas en contienda dentro de ti, y no más de dos?
No hay una tercera o cuarta, sino solo dos; y debes unirte a una o a otra.
Estoy seguro de que no eres del todo ignorante,
sino que tienes conocimiento y discernimiento de que esto es así, a saber,
de que hay dos naturalezas o semillas en ti, una que te atrae e invita hacia lo bueno,
y otra que te atrae hacia lo malo.
A una de estas dos debes entregarte en obediencia; a cualquiera que obedezcas,
para esa también siembras, y con esa debes cosechar.
Tú no lees en las Escrituras, ni encuentras en ti mismo,
dos luces o dos semillas buenas que se opongan a la única semilla maligna de oscuridad;
sino más bien una luz o semilla, que es la luz de Cristo,
quien es la Semilla de la mujer que se menciona en la Escritura.
Esta se opone a la única naturaleza o semilla de oscuridad en ti, y no encontrarás otra.
Así que eso que te atrae hacia fuera, a buscar otra luz o poder,
es la serpiente y su semilla, unidas a tu mente carnal,
la cual busca desprenderte de la verdadera luz y Semilla--que es
Cristo--a fin de que la serpiente manifieste su voluntad en ti,
a través de su naturaleza y semilla de oscuridad.

Por lo tanto, no tienes que tener ninguna duda o dificultad en este asunto,
a menos que voluntariamente provoques que venga sobre
ti por abusar de eso que ya es cierto en ti,
y no usar la luz de Cristo para el fin por el cual fue puesta en tu corazón.
Porque nunca has hallado esta luz o semilla en ti consintiendo ningún mal,
ni justificándote en la práctica de ninguna cosa mala.
Así que es seguro y bueno para ti aferrarte a eso que es cierto y seguro,
y dejar de lado eso que no es cierto.
En verdad, Dios requiere tu obediencia a eso que es cierto, y no a eso que no es cierto;
a eso que tiene su fundamento en tu propia consciencia y en las Escrituras,
y no a eso que no tiene fundamento ni en las Escrituras ni en tu consciencia.
Ya tienes un fundamento suficiente para creer en esta luz en ti y para entregarte a ella,
debido a la certeza de su presencia en tu corazón, y a la pureza de su naturaleza en ti;
y porque ella da una prueba evidente de sí misma,
y de su tendencia a llevarte hacia la Fuente de luz y vida de la que viene.
Y ella también permanece como un testigo fiel contra toda maldad,
que nunca consiente el mal en pensamiento, palabra u obra,
sino que testifica contra estas cosas, y contra ti en ellas,
llamándote a volverte de la maldad de tu camino,
y a menudo poniendo delante de ti el peligro de continuar
en él. Además te convence de la misericordia,
cuidado, ternura, longanimidad y paciencia de Dios para contigo,
dejándote ver los muchos peligros y riesgos de los cuales has sido librado,
y los muchos pensamientos e intenciones secretos que has escondido de los hombres.

Sí, la luz está al tanto de todas estas cosas, y sin embargo,
a pesar del mal que has hecho,
estás consiente en tu corazón de que esta luz permanece en ti,
esforzándose por recuperarte durante el día de tu visitación,
y por sacarte de todos los males a una nueva vida.
E independientemente de todas tus provocaciones,
y de tus muchas rebeliones contra esta luz, aun así,
el amor de Dios en Cristo ha entrado en tu corazón en esta luz;
porque cuando tú has estado enfermo, o en cualquier angustia o aflicción,
esta luz ha movido tu mente a mirar a Dios, y a considerar tus antiguos caminos.
Sí, te ha movido a enmendar tu vida, y ha puesto la misericordia,
amor y perdón de Dios ante tus ojos, bajo la condición de que te arrepientas.
Y, por lo tanto, tienes un buen fundamento para creer en la luz,
habiendo sentido poder y fuerza en ella para convencerte del bien y del mal.

E independientemente de las operaciones sutiles de la serpiente,
y de tu propia mente carnal que obran en su contra,
esta luz es más fuerte que toda oposición, e irrumpe en tu corazón sobre todas las cosas,
mostrándote muchas cosas que son agradables para Dios,
y también convenciéndote de muchas cosas que son desagradables para Él. De modo que,
ni la serpiente ni tu propio corazón malvado pueden impedir que esta luz brille,
ni pueden hacer que ella pare de convencerte de que Dios existe, y de que debe ser amado,
temido y obedecido--ni de mostrarte tus muchos males.
Y por ende,
es verdad que "`la vida y la muerte han sido puestas delante
de ti,`" y que en la luz puedes "`escoger la vida y vivir.`"^
footnote:[Deuteronomio 30:15-19]
Pero si después de que la vida y la muerte han sido puestas delante de ti,
desechas la vida por rechazar la luz,
entonces la muerte crecerá en tu corazón y la luz se volverá tu condenación.
Y por tu propia boca serás condenado y obligado a reconocer,
que no carecías de una luz verdadera y salvadora, ni te faltaba poder para obedecerla,
o para obtener vida al andar en ella,
en los tiempos y sazones de vida que te fueron ofrecidos en el día de tu visitación.

Por lo tanto, todos aprecien su tiempo.
Teman y permanezcan en reverencia ante el Señor, y usen bien cada tiempo,
estación y oportunidad de vida.
Porque he aquí, el Juez--Jesucristo--está a la puerta: "`Yo estoy a la puerta y llamo;
si alguno oye Mi voz y abre la puerta, entraré a él, y cenaré con él, y él conmigo.`"^
footnote:[Apocalipsis 3:20]
Cada vez que son golpeados por algún mal y son llamados a abandonarlo,
y por lo tanto a volverse al Señor; les digo, cada vez que esto sucede,
es un toque de Cristo llamando a la puerta de sus corazones.
Es Su voz la que los llama a salir del mal y a abandonarlo,
a fin de que puedan abrazar el bien,
y aferrarse a él con su corazón. Y con la luz ustedes
también verán cómo han pasado por alto muchos tiempos,
estaciones y oportunidades de vida, en los que Cristo, su Juez, ha venido a sus puertas,
es decir, a sus corazones, y ha estado tocando,
pero ustedes no creyeron que fuera Él. Así que ahora, aprecien el tiempo que les queda,
y tengan cuidado de no hacer esto más,
no sea que Él se aparte de sus corazones y los deje sin convicción ni reprensión,
sin llamados ni toques.
Pero mientras Él esté a la puerta de sus corazones, convenciéndolos y reprobándolos,
y llamándolos a salir del mal y a entrar al bien,
hagan uso de estos tiempos y estaciones, y tengan cuidado de no despreciarlos más.

Por lo tanto,
ábranse a Él mediante una obediencia verdadera y sincera--esa obediencia
que es de la fe en Él --a medida que Él aparece en sus corazones.
Porque si ustedes creen que esta es Su luz, y por lo tanto,
lo obedecen a Él en esta creencia, entonces,
a través de esta obediencia de fe sentirán gozo y
paz brotando para la alegría de sus almas.

Nada más por el momento,
pero sigo siendo un amigo que desea buena salud para sus almas y para sus cuerpos.

[.signed-section-signature]
Patrick Livingston

[.signed-section-context-close]
Desde la prisión de la Casa de Hierro

[.asterism]
'''

Patrick Livingston nació en el año 1634, cerca de Montrose, en Escocia,
y fue convencido de la verdad, tal como era sostenida por el pueblo llamado Cuáqueros,
alrededor del año 1659, después de lo cual, él y otras siete personas más,
mantuvieron una reunión por un largo tiempo en una pequeña aldea llamada Emeldown.
Al continuar en humilde sumisión al poder de la gracia que cambia el corazón,
se convirtió en uno de los principales instrumentos
que fueron usados en las partes del norte de Escocia,
para reunir a muchos de las montañas estériles de vacía profesión religiosa,
y llevarlos a ser alimentados de los pastos verdes
de vida bajo la guía del Pastor de Israel.

En el año 1664, cuando iba a visitar a sus hermanos en Aberdeen en el amor del evangelio,
fue echado en prisión y detenido siete meses.
Después de ser puesto en libertad,
siguió laborando diligentemente para el evangelio en el norte de Escocia,
viajando varias veces por todos esos lugares,
y sufriendo mucho en Aberdeen como prisionero por su testimonio,
durante el tiempo de la severa persecución contra los Amigos en esa ciudad.
En el año 1669,
para el gran perjuicio de sus asuntos temporales y la terrible prueba de su joven esposa,
fue arrestado por reunirse con sus amigos para adorar al Señor,
y encerrado en una asquerosa prisión por tres años enteros;
durante todo ese tiempo nunca fue llamado a comparecer ante ningún juez o corte,
para que se presentara o probara una acusación contra él.

Como una muestra de la nobleza y del inquebrantable coraje
de este fiel hombre durante su extendido confinamiento,
se adjunta el siguiente extracto.
Fue tomado de una apelación que escribió a sus perseguidores desde la cárcel, titulado,
_"`Respecto a la Verdadera Adoración de Dios.`"_

[.embedded-content-document.address]
--

Pero sin importar lo que suframos,
no podemos darle a ningún hombre u hombres lo que únicamente le pertenece a Cristo,
y lo que únicamente Él tiene derecho a recibir,
el cual pone Su Espíritu en nosotros a fin de establecer
Su propia adoración en nosotros y guiarnos en ella.
Y tenemos gran gozo y satisfacción en nuestros sufrimientos por este testimonio,
aunque los hombres se llenen de ira contra nosotros y nos encierren en asquerosos huecos;
porque nosotros sabemos que el testimonio que damos es verdadero y fiel, y por lo tanto,
estamos alegres en nuestros sufrimientos por él.

Ahora bien, según sus propios procedimientos con ladrones y homicidas,
ustedes los llaman a comparecer en la corte y los juzgan por la ley,
y traen testigos para probar los hechos contra ellos, los cuales,
si no pueden ser probados, los sospechosos deben ser puestos en libertad,
aunque sean acusados de delitos graves.
Pero en cuanto a mí,
a pesar de que he sido prisionero durante aproximadamente veinte meses,
hasta este momento nunca he sido llamado legalmente ante el tribunal,
ni se me ha acusado de nada,
ni se ha presentado ningún testigo contra mí para probar el incumplimiento de alguna ley.
Y en verdad puedo decir, que no estoy consciente de haber incumplido alguna ley,
y me veo obligado a mantener esta opinión hasta que sea convencido de lo contrario.
¿Existe alguna ley en este reino que nos prohíba reunirnos
en nuestras propias casas para adorar a Dios?
Si existe una ley como esta, no me negaré a sufrir el castigo de ella;
sino todo lo contrario,
estoy dispuesto a soportarlo pacientemente sin hacer resistencia con algún arma carnal;
pero manifiesto ser ignorante de una ley como esta.

Ahora declaro, en la verdad de mi corazón, delante del Señor,
que antes de inclinarme o someterme a tal espíritu de usurpación,
que no solo roba nuestros derechos y privilegios como hombres y como cristianos,
sino también el privilegio y derecho de Jesucristo en nosotros,
y pretende establecer la voluntad del hombre en el lugar de Jesucristo,
obligándonos a adorar de manera contraria a nuestra consciencia
en la voluntad del hombre--yo digo y declaro,
que prefiero ofrecer mi cuerpo y dejarlo en esta prisión,
y nunca en mi vida volver a mi querida esposa,
(quien creo que preferiría antes verme morir en prisión como un hombre
fiel por el amor de Cristo) que vivir con ella como un hombre infiel.
Porque, dado que nos hemos unido en el amor de la verdad,
mediante la fe en ella y la fidelidad a ella,
sería mejor para mí y para mi querida esposa que
muriera en prisión como un hombre fiel a Cristo,
que someterme a ese espíritu maligno y opresivo,
y desechar mi derecho natural como hombre y como Cristiano.
Porque esto sería negar a mi Señor y Maestro ante los hombres,
si con el fin de obtener mi libertad natural y regresar a casa con mi esposa,
desechara mi libertad espiritual en Cristo,
y Su derecho a reinar sobre mí. ¿No sería esto negarlo a Él,
y amar mi vida natural más que a Él,
y amar mi libertad natural y a mi esposa más que a Él? ¿Y si yo hiciera esto,
¿qué consuelo tendría mi querida esposa de mí?

Mientras que ahora puedo decir verdaderamente,
que mi alma se regocija en el Señor Jesucristo,
y que a menudo soy refrescado y consolado por las cartas que recibo de mi querida esposa,
quien no es un desaliento sino un aliento para mí en mis sufrimientos.
Es por amor a Cristo y por Su testimonio, que estamos separados por un tiempo,
y no por ningún motivo o ventaja terrenal, el Señor lo sabe;
y nos encontraremos otra vez en el tiempo del Señor, para nuestro gozo y consuelo mutuo.
Porque aunque está escrito que:
"`Si alguno no provee para su familia es peor que un incrédulo,`" aun así,
el Señor Jesús también dice: "`El que ama padre o madre, esposa o hijos,
o su propia vida más que a Mí, no es digno de Mí.`" Y puedo decir verdaderamente,
que no me he quedado en este lugar por mi propia voluntad,
sino más bien en la cruz a mi voluntad; y todos pueden juzgar fácilmente,
que no es muy placentero para el hombre natural ser encerrado
por tanto tiempo en un lugar tan asqueroso como este.

--

Durante el estricto encarcelamiento de Amigos en el Tolbooth de Aberdeen,
Patrick Livingston era uno de los más frecuentemente movidos,
en el abundante amor Cristiano,
a predicar por las ventanas de la prisión a las personas que estaban fuera,
especialmente en los días de mercado,
exhortándolos a temer al Señor y a obedecer el evangelio de Su gracia.
Esta práctica era muy desagradable para los magistrados, y por lo tanto,
trataban de impedirla,
haciendo que esos predicadores fueran separados del resto de sus compañeros,
echándolos violentamente a una celda cerrada situada en la parte
más elevada de la cárcel que llamaban la Casa de Hierro,
donde usualmente se confinaban a los peores criminales y asesinos.
Allí no tenían ni luz ni aire, salvo por un largo hueco en el grueso muro,
que tenía una reja doble de hierro,
una en la parte de afuera y otra en la parte de adentro.
Patrick Livingston fue encerrado aquí noche y día, en el calor del verano de 1678,
tiempo durante el cual la inmundicia del lugar y la degradación del aire retenido,
produjeron una multitud de gusanos blancos y otras alimañas,
que abundaban en todas partes, incluso sobre sus camas y comida, lo cual,
evidentemente tendía a poner la salud y la vida de ellos en peligro extremo.
Es respecto a esta crueldad que Patrick Livingston escribe en el siguiente extracto:

[.embedded-content-document.address]
--

Y en el noveno día de este mes, 1678,
siendo movido a hablar algunas palabras de verdad
y sobriedad desde la ventana de la prisión,
los oficiales vinieron a la celda en la que estaba,
y me dijeron que tenían órdenes del alguacil Burnett de encerrarme en
la Casa de Hierro noche y día. Yo solicité ir a hablar con el alguacil,
o al menos ver una línea escrita por su mano que mostrara que esa era su orden,
pero como no estuvieron dispuestos a ir a solicitarla,
me negué a ir a la Casa de Hierro por orden de ellos para ser encerrado
noche y día. Y por eso los oficiales me cogieron de mi cabeza y pies,
y me arrastraron con mi cabeza hacia abajo y mis
pies hacia arriba hasta el tope de las escaleras.
George Gray fue echado a la misma celda conmigo por hablarles a las personas,
y poco tiempo después y por la misma razón,
Andrew Jaffray fue llevado también a la Casa de Hierro,
donde fuimos encarcelados juntos y nos cerraron la puerta noche y día,
y no nos permitieron ir a la otra celda a comer con nuestros Amigos.

Ahora bien, este trato cruel y duro hacia mí no es tan sorprendente,
porque no soy de su ciudad, sino que, en cierto modo, soy un extranjero para ellos.
Pero ellos también pusieron a estos dos hombres en prisión conmigo; +++[+++George Gray,
y Andrew Jaffray]
y ambos ocuparon cargos entre ellos, uno como magistrado y otro como decano de gremio,
hombres de buena estima entre ellos, en todos los aspectos.
Y para añadir aún más a todo esto, el padre de Andrew Jaffray^
footnote:[Alexander Jaffray (1614-1673). Véase el diario de Alexander Jaffray]
era un hombre de muy buena estima entre ellos, como magistrado principal de la ciudad.
Era considerado por todos como un hombre muy religioso,
de buena fama en su iglesia en su momento más estricto,
y elogiado como alguien que había hecho bien por su ciudad más
allá de muchos antes que él o después que él. Y sin embargo,
algunos son tan olvidadizos de estos antiguos servicios por el bien público,
que en retribución a dichos servicios,
su hijo mayor ha sido encerrado noche y día en su Casa de Hierro,
que es un hueco apestoso y asqueroso, donde normalmente no se ha puesto a nadie,
aparte de asesinos y terribles malhechores a quienes desean tener asegurados.

Y ahora bien, si así tiene que ser,
que todos o algunos de nosotros tuviéramos que morir por estos
tratos tan duros (que creo que no sucederá en este momento),
aun así, eso no vencería nuestra fe.
Porque Abel vivió y murió en la fe; y aunque Caín lo mató,
no fue capaz de vencer o matar la fe de Abel.
Y aunque como hombres,
ustedes creen que tenernos encerrados en estos asquerosos
huecos no beneficia a nuestro hombre natural,
sino que lo desgasta y es una especie de martirio prolongado, aun así,
en cuanto a nuestro hombre interior, estamos creciendo diariamente en poder,
dominio y fuerza; de modo que, matar al hombre natural no vence al espiritual,
sino que todavía vivimos y nos hacemos más fuertes
en esa vida contra la cual ustedes están enemistados.
Y por lo tanto, ustedes no pueden lograr su objetivo,
independientemente de lo que suceda con nuestro hombre natural;
porque todo lo que pueden tocar es al hombre exterior, e incluso,
no lo pueden tocar más allá de lo que nuestro Padre celestial
permita para nuestro bien y para la gloria de Su Nombre;
p ero ustedes no pueden tocar a nuestro hombre espiritual, hagan lo que hagan.
Y cuando hayamos terminado nuestro curso,
y corrido hasta el final la carrera puesta delante de nosotros por el Señor Jesús,
y hayamos recostado nuestras cabezas en paz, aun así,
la Vida de Jesús que se manifiesta diariamente en nuestros
cuerpos mortales (que ha estado en nosotros y con nosotros,
como la fuerza de nuestros corazones en todos nuestros sufrimientos,
pruebas y tentaciones, internos y externos,
y conforme seamos fieles estará en y con nosotros hasta el fin de nuestro días)--digo,
después de que hayamos partido,
esta misma Vida de Jesús levantará a otros que vendrán después de nosotros,
y ningún poder de persecución será capaz de detenerla.
Porque la senda del justo, como la luz de la aurora,
va en aumento hasta que el día es perfecto.
Y el testimonio que llevamos actualmente será hallado verdadero,
y muchos en los siglos venideros lo certificarán,
y los niños que ahora juegan en sus calles vendrán y certificarán nuestro testimonio,
afirmando que es verdadero, y de Dios, y no de nosotros mismos.
Y el nombre y la fama de todos los perseguidores vivirá
como un mal olor para muchos que vendrán después,
pero la memoria del justo será un dulce olor para muchas personas.

Pero tomen nota de esta única cosa: que en cada época,
dondequiera que vivan buenas personas,
son odiadas y perseguidas por aquellos que viven en esa época,
pero no están bien con Dios en sus propios corazones.
Y los perseguidores de las buenas personas en la época presente,
siempre clamarán contra los perseguidores de las épocas antiguas,
y elogiarán a los hombres santos que sufrieron en los tiempos anteriores;
pero no están dispuestos a creer que aquellos a quienes
persiguen en su propia época y tiempo son el pueblo de Dios.
Y así como es con los perseguidores de nuestra época,
ha sido con los perseguidores de cada época;
exaltan y elogian a los fieles mártires del pasado, y claman contra sus perseguidores.
Pero estos de ninguna manera creerán que a los que persiguen hoy sean un pueblo inocente;
al contrario, los llaman malhechores; ni se llaman a sí mismos perseguidores.
En verdad, nunca ha habido un perseguidor en el tiempo de su persecución,
que se haya reconocido a sí mismo como tal,
ni a los que persigue como inocentes mártires.
Pero de esto no diré más, habiendo hablado de ello muy ampliamente en otro lugar.
Y por lo tanto, los encomiendo todos a la gracia de Dios en sus propios corazones,
para que ella les enseñe a negar y a dejar toda impiedad y deseos mundanos,
y a vivir sobria y justamente en este mundo presente.

[.signed-section-closing]
De un amigo de todas sus almas,

[.signed-section-signature]
Patrick Livingston.

[.signed-section-context-close]
Escrito desde la Prisión en Aberdeen

--

[.asterism]
'''

__Aparte de las varias y largas detenciones en prisiones de Escocia,
Patrick Livingston también fue encarcelado por un tiempo considerable en Newgate,
Londres, cerca del año 1684.
En sus últimos años, se fue de Nottingham,
donde había residido por algún tiempo y se mudó con su familia a Londres.
Allí continuó siendo un obrero diligente en la viña del Señor,
viajando en el servicio del evangelio por muchas partes de Inglaterra e Irlanda,
y visitando Escocia en varias ocasiones.
De su última visita a su tierra nativa en el año 1693, el año antes de su muerte,
se dijo, que de todas las veces que había estado entre ellos,
en esa oportunidad su ministerio había sido acompañado con
la medida más grande y más plena del bendito poder del Señor,
que jamás habían visto.
En verdad, él fue maravillosamente sostenido por encima de todos los obstáculos,
aunque su cuerpo estaba muy débil; de modo que,
algunos llegaron a hablar de este último acto de servicio,
como "`su cariñosa despedida de su parentela espiritual.`"__

__Muy pronto después de su regreso a casa de este viaje, se fue debilitando cada vez más,
hasta que partió de esta vida el día 15 del cuarto mes de 1694,
en la casa de John Kirton, en Kensington, cerca de Londres.
Varios Amigos estuvieron presentes con él en sus últimas horas,
tiempo durante el cual las siguientes expresiones
celestiales fluyeron de él. El día antes de su partida,
dijo: "`Estoy en unidad con todos los Amigos fieles, y en amor a todos los hombres.`"
Y alrededor de una hora antes de su final, clamó:"`¡Oh Padre! ¡Oh Padre!
Permite que la Vida alcance a todos aquí!`" Entonces
quitándose su gorro para dormir con su propia mano,
como treinta minutos antes de dejar de respirar, dijo:"`Bendito, alabado,
magnificado y exaltado sea el alto, poderoso, grande y eterno nombre del Señor Dios,
por siempre.
¡Oh!
Que Tú Vida se levante en pleno dominio sobre todos,
y que los Amigos la sientan así en todas sus reuniones;
para que ellos puedan mantenerse en amor, concordia y unidad juntos,
y lo demuestren en palabra, obra, testimonio,
vida y conducta a todos!`"--y entonces añadió: "`¡Oh que Tú vida sea sobre todo,
porque así tenemos todo lo que necesitamos,
y así hay un reposo en verdadera sumisión a la voluntad del Señor,
en el que recostamos nuestras cabezas en paz y descanso con Él para siempre.
Aquí se encuentra la verdadera victoria sobre la muerte, el infierno y el sepulcro,
y un descanso en paz con el Señor por siempre!`"__
